os: linux
language: node_js
notifications:
  slack:
    template:
      # This template config somehow breaks yaml syntax
      # in the editor although it is valid yaml syntax
      - "Project: lyne-helper-trigger-travis"
      - "Build: <%{build_url}|%{build_number}>"
      - "Commit: <%{compare_url}|%{commit}>"
      - "Author: %{author}"
      - "Result: %{result} in %{duration}"
    secure: F/SdCBZnPY4/ZdQV/JkBKnQ8K1Q+jqPSeK4WNVEgV3pKh0XMZoOsIEdcj66KLXH/i9nokJ5zd0uDq1azzN7dTbPfgGJnvWeXjt3jvfwYCLNoRZ9IkW+LylGLCYSpftmuF3HmFu9EvK7X6fxms9nxRzVC8NhfNBpvPN2zbTBhsGerDzdVHwdpChJd+bch7HCq3SS2DxOIJytQJtIohuQ5R3m8RxHK1el5CRX/fy9g+AXzzRqyJlF+M1N+Ie4maImphQgRjfsMfijBqqvJiMRsG0FILfyUhvI9SR6IvmCuOT1KqIVaNqZH8X+SMUqLsIVwXZm+coXNffkDsrWQfSdhpVS0YQ4M9Yk9NEyJ9jVgDOD27NOEGUZkJpLjIpofImCMb3Td8bjlbXeWf+JvEQx/O58jT/jg7RSs2Jto9qXwfSw8s6QW6WIBURkI5zhM2ihZHE5o0/dhJFGCzTQgdCz0kEMttsqar5TuNKdCAI2OnlHCaLgRMqXvewRafojHKE5yB22IEUv56SofQw12z+DTfMVt77U4tQWfIwUGjlwhlLq9qJOj6icGwkFM6qThSI12eFnkAU1JImqYWRyAA1ZPO9mJdkZpZWIUiEadVye4NorkeADa6QFzyQRuE69tQkElgs7LVscIjRU2B3bQngrMkcOKc9sBBQYHvEuHJIy0yHE=
jobs:
  include:
    - stage: build and deploy package
      script:
      - npm run lint
      - npm run trigger

      after_success:
      - npm run semantic-release
